### ISSUE TITLE
Old dead ish still hanging around

### ISSUE THREAD

**Issue by nh36** [knightss27/capr#13]
My understanding is that a dead fish should only appear if, according to the current transducers, one of the items on that column cannot be reconstructed to proto-Burmish. So, if a column only has one item, then it shouldn't have a dead fish on it. But there are currently lots of those examples. So, I would suggest that as part of the refishing process all the old fishes (whether dead or alive) are first removed, and then assigned afresh.

**Comment by knightss27** [comment]
Let me see what Xun's code is doing to decide what gets these fishes. Hopefully I can clear this up.

**Comment by nh36** [comment]
I have found a work around. Which is to put dead fish on the pinning spot and then clear the pinning spot. So, no urgency at all at all. Actually, I think it is correct the way it is being done, because it allows me to decide what is on each board. So I am closing. the issue.
