### ISSUE TITLE
Missing Libraries in Installation

### ISSUE THREAD

**Issue by LinguList** [knightss27/capr#14]
@knightss27, this looks like really great work to me. Was it your idea to use node for the editing process? This runs very smoothly as far as I can tell by now.

What I would like to mention is that the current package misses a list of required packages, a `requirements.txt` file. When trying to check the node and the dev-mode, using flask, I had to install another flask package that was not mentioned.

To avoid this, I suggest you make a virtual environment with Python and test with this environment. If all works, you then make `pip freeze > requirements.txt`. In this way, I can make a fresh environment later and type `pip install -r requirements.txt` and it will run without problems (provided foma is installed).

**Comment by LinguList** [comment]
Ah, I figured one more problem with the file `output`, which the server was looking for, but which was not where it was supposed to be, when testing the node application from within the `server` directory.

**Comment by knightss27** [comment]
Yes, I had been meaning to make a requirements file but had not gotten round to it. I can add that soon. Also I moved the output directory when cleaning up so I'm not surprised I had one of the paths messed up. I can double check those as well.

**Comment by knightss27** [comment]
Also, by "using node in the editing process" do you mean just the front-end part of the program? The original front-end was written in React (JavaScript framework) so I just continued in the same vein, but I switched frameworks to Svelte because I dislike React and find it to be overbearing especially on smaller projects.

**Comment by LinguList** [comment]
I mean the front end.

**Comment by LinguList** [comment]
I use private front-ends with electron, but would not use them to deploy methods, but therefore, I know it is quite useful for small apps.

**Comment by LinguList** [comment]
I did not know the one you use, though.

**Comment by knightss27** [comment]
Yes, I had thought about putting this all into an Electron app, though I have never used Electron so didn't have time to try. Also I am not surprised you haven't heard of Svelte, it is not as popular as others, but it is quite unique as it is really a compiler that takes all of my code and spits out native JavaScript (which frameworks like React do not). You can probably tell by looking at my other GitHub repos that I enjoy it!
